package:
  name: deckbridge
  version: "0.1.0"

source:
  path: ../

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
  run:
    - python>=3.9
    - google-api-python-client
    - google-auth
    - google-auth-httplib2
    - google-auth-oauthlib
    - pandas
    - python-pptx

test:
  imports:
    - pandas
